apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: csharp-host
  namespace: org-services
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - open-source-host.openvasp-enterprise.ch
    secretName: csharp-host-tls
  rules:
  - host: open-source-host.openvasp-enterprise.ch
    http:
      paths:
      - backend:
          serviceName: csharp-host
          servicePort: 80
